sonar.projectKey=velour-and-vine
sonar.projectName=Velour and Vine
sonar.projectVersion=1.0
sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,**/*.spec.js,**/*.test.js,**/__tests__/**
sonar.language=js
sonar.sourceEncoding=UTF-8
